spring:
  profiles:
    active: default

  redis:
    host: localhost
    port: 6379
    password: 9876
    timeout: 3000
    lettuce:
      pool:
        max-active: 300
        max-idle: 300
        max-wait: -1
        min-idle: 10

---
spring:
  profiles: default

  redis:
    host: localhost
    port: 6379
    password: 9876
    timeout: 3000
    lettuce:
      pool:
        max-active: 300
        max-idle: 300
        max-wait: -1
        min-idle: 10